server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: yue-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yue_picture
    username: root
    password: 2004
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境开启打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-not-delete-value: 0 # 逻辑未删除值
      logic-delete-value: 1 # 逻辑删除值
#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yue.yuepicturebackend.controller